[package]
name = "discord"
edition = "2021"
version.workspace = true


[dependencies]
error-stack.workspace = true
poise.workspace = true
tokio.workspace = true
tracing.workspace = true
shakmaty.workspace = true
backend = { path = "../backend" }
rand = "0.8.5"
